"""One to many relationship between orgarnisation and job offers

Revision ID: 12156354071f
Revises: 5e901aaee310
Create Date: 2025-05-29 22:16:26.854988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12156354071f'
down_revision: Union[str, None] = '5e901aaee310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_offers', 'organizations', ['organization_id'], ['id'])
    op.alter_column('roles', 'value',
               existing_type=mysql.VARCHAR(length=19),
               type_=sa.Enum('ADMIN', 'ORGANIZATION_OWNER', 'RECRUITER', 'MODERATOR', 'APPLICANT', name='role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'value',
               existing_type=sa.Enum('ADMIN', 'ORGANIZATION_OWNER', 'RECRUITER', 'MODERATOR', 'APPLICANT', name='role', native_enum=False),
               type_=mysql.VARCHAR(length=19),
               existing_nullable=False)
    op.drop_constraint(None, 'job_offers', type_='foreignkey')
    op.drop_column('job_offers', 'organization_id')
    # ### end Alembic commands ###
