"""Capture file ext as well

Revision ID: 17a12580e7bd
Revises: ecdecfb03afd
Create Date: 2025-06-04 18:46:53.729116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a12580e7bd'
down_revision: Union[str, None] = 'ecdecfb03afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ext', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ext')
    # ### end Alembic commands ###
