"""Remove email index

Revision ID: 5a825e54232c
Revises: 822a271a72ab
Create Date: 2025-05-29 23:33:38.830756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a825e54232c'
down_revision: Union[str, None] = '822a271a72ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('Pending', 'Rejected', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('Pending', 'Rejected', name='status', native_enum=False),
               existing_nullable=False)
    op.alter_column('users_applications', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'APPROVED', name='status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_applications', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', name='status', native_enum=False),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('Pending', 'Rejected', name='status', native_enum=False),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('organizations', 'status',
               existing_type=sa.Enum('Pending', 'Rejected', name='status', native_enum=False),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
