"""Remove relation between users and addresses

Revision ID: 822a271a72ab
Revises: 12156354071f
Create Date: 2025-05-29 22:17:25.351980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '822a271a72ab'
down_revision: Union[str, None] = '12156354071f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_ibfk_1', 'users', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###
