"""Make job offer value str and not enum

Revision ID: 9f613380f49e
Revises: c2c347eb2510
Create Date: 2025-06-02 23:13:18.099523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f613380f49e'
down_revision: Union[str, None] = 'c2c347eb2510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_tags', 'value',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_job_tags_value'), 'job_tags', ['value'], unique=True)
    op.add_column('users_applications', sa.Column('cv_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_applications', 'cv_url')
    op.drop_index(op.f('ix_job_tags_value'), table_name='job_tags')
    op.alter_column('job_tags', 'value',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
