"""Update users_applications table. New resume table for blobs. New relation between users and resume

Revision ID: d2111bdb0807
Revises: 9f613380f49e
Create Date: 2025-06-04 11:13:03.735587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2111bdb0807'
down_revision: Union[str, None] = '9f613380f49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.add_column('users_applications', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('users_applications', sa.Column('application_date', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'users_applications', 'resumes', ['resume_id'], ['id'])
    op.drop_column('users_applications', 'cv_url')
    op.drop_column('users_applications', 'applied_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_applications', sa.Column('applied_at', mysql.DATETIME(), nullable=True))
    op.add_column('users_applications', sa.Column('cv_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users_applications', type_='foreignkey')
    op.drop_column('users_applications', 'application_date')
    op.drop_column('users_applications', 'resume_id')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
