"""Remove organization phone number

Revision ID: e6ca36668b13
Revises: 74eb87971a47
Create Date: 2025-05-31 23:37:51.858328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6ca36668b13'
down_revision: Union[str, None] = '74eb87971a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone_number', mysql.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
