"""Add resumes table

Revision ID: ecdecfb03afd
Revises: d2111bdb0807
Create Date: 2025-06-04 14:28:02.772443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecdecfb03afd'
down_revision: Union[str, None] = 'd2111bdb0807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(length=50), nullable=False))
    op.add_column('resumes', sa.Column('content_type', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.alter_column('resumes', 'title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('resumes', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('data', sa.BLOB(), nullable=False))
    op.alter_column('resumes', 'title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('resumes', 'content')
    op.drop_column('resumes', 'content_type')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
