version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_hunter
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --max_allowed_packet=512M

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: job_hunter
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
